import * as z from 'zod';

export const customerSchema = z.object({
  // TAB 1: Customer Details + Package Details
  fullName: z.string().min(2, 'Name must be at least 2 characters'),
  customerType: z.string().min(1, 'Please select Customer Type'),
  contactNumber: z.string().min(10, 'Contact number is required'),
  pocNumber: z.string().optional(),
  email: z.string().email('Invalid email').optional().or(z.literal('')),
  cnic: z.string().min(13, 'CNIC number is required'),
  cnicExpiry: z.string().optional(),
  passportNumber: z.string().optional(),
  ntnNumber: z.string().optional(),
  houseNo: z.string().optional(),
  streetNo: z.string().optional(),
  block: z.string().optional(),
  subArea: z.string().optional(),
  area: z.string().optional(),
  city: z.string().min(1, 'Please select or type a City'),
  country: z.string().default('Pakistan'),
  coordinates: z.string().optional(),
  address: z.string().min(3, 'Address is required'),
  signUpDate: z.string().optional(),
  customerStatus: z.string().default('SIGNUP_GENERATED'),
  accountExecutiveId: z.string().optional(),
  accountExecutiveName: z.string().optional(),

  // Package Details (Section 2 in Tab 1)
  systemSizeKw: z.string().min(1, 'Please select System Capacity'),
  packageTier: z.string().min(1, 'Please select Package Tier'),
  billingType: z.string().min(1, 'Please select Billing Type'),
  monitoringTime: z.string().min(1, 'Please select Monitoring Time'),
  monthlyBasePrice: z.coerce.number().default(0),
  salesTaxAmount: z.coerce.number().default(0),
  onboardingFee: z.coerce.number().default(0),
  totalAmount: z.coerce.number().default(0),
  paidAmount: z.coerce.number().default(0),
  paymentMode: z.string().optional(),
  paymentDescription: z.string().optional(),

  // TAB 2: Solar System Details (Optional defaults for technical specs)
  meterType: z.string().optional(),
  zeroExportDevice: z.string().optional(),
  disco: z.string().optional(),
  discoRefNo: z.string().optional(),
  inverterBrand: z.string().optional(),
  inverterType: z.string().optional(),
  inverterPhase: z.string().optional(),
  noOfInverters: z.coerce.number().default(0),
  inverterSerial: z.string().optional(),
  inverterCategory: z.string().optional(),
  inverterSize: z.string().optional(),
  inverterWarrantyExpiry: z.string().optional(),
  meterPhase: z.string().optional(),
  panelTechnology: z.string().optional(),
  panelBrand: z.string().optional(),
  panelWattage: z.coerce.number().default(0),
  noOfPanels: z.coerce.number().default(0),
  panelType: z.string().optional(),
  panelWarrantyExpiry: z.string().optional(),
  batteryCategory: z.string().optional(),
  batteryType: z.string().optional(),
  batteryBrand: z.string().optional(),
  noOfBatteries: z.coerce.number().default(0),
  batteryWarrantyExpiry: z.string().optional(),
  earthingType: z.string().optional(),
  earthingOhms: z.string().default('0'),
  lastCheckDate: z.string().optional(),
  ingressProtection: z.string().optional(),
  structureType: z.string().optional(),
  structureMaterial: z.string().optional(),
  installationDate: z.string().optional(),

  // TAB 3: Installer Details & System Audit (Optional at initial sale intake)
  installerName: z.string().optional(),
  installerCompany: z.string().optional(),
  installerAddress: z.string().optional(),
  installerContact: z.string().optional(),
  installerEmail: z.string().optional(),
  lastAuditDate: z.string().optional(),
  inverterAuditStatus: z.string().optional(),
  panelAuditStatus: z.string().optional(),
  batteryAuditStatus: z.string().optional(),
  structureAuditStatus: z.string().optional(),
  cableAuditStatus: z.string().optional(),
  earthingAuditStatus: z.string().optional(),
  breakersAuditStatus: z.string().optional(),
});
